version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_rpm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpm_customer
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
  discovery:
    build: ./rpm-discovery
    image: rpm-discovery
    environment:
      SERVER_PORT: 8761
    ports:
      - "8761:8761"
  gateway:
    build: ./rpm-gateway
    container_name: rpm-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: my-super-secret-key-should-be-very-long-and-secure
      EUREKA_URL: http://discovery:8761/eureka

  auth-service:
    build: ./rpm-auth-ms
    container_name: rpm-auth
    # ports:
    #   - "8081:8080"
    depends_on:
      - discovery
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: my-super-secret-key-should-be-very-long-and-secure
      EUREKA_URL: http://discovery:8761/eureka

  customer-service:
    build: ./rpm-customer-ms
    container_name: rpm-customer
    # ports:
    #   - "8082:8080"
    depends_on:
      - discovery
      - mysql
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:mysql://mysql:3306/rpm_customer
      DB_USER: appuser
      DB_PASSWORD: apppass
      EUREKA_URL: http://discovery:8761/eureka

volumes:
  mysql_data:
