spring:
  application:
    name: auth-service

security:
  auth:
    username: admin
    password: $2a$12$ljxDdmOyw.xLcOjwXkUvzePxdhLqh7caP1hibQSyfD7wE6pOfSk0G
# real pass: 123456

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-should-be-very-long-and-secure}

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka/}
