spring:
  application:
    name: RPM Discovery server

server:
  port: ${SERVER_PORT:9000}
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # service-url:
    #   defaultZone: ${EUREKA_URL:http://localhost:9000/eureka}
  server:
    enable-self-preservation: false

    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
    response-cache-update-interval-ms: 60000
    response-cache-auto-expiration-in-seconds: 180
  dashboard:
    enabled: false


